### PR TITLE
multiple contract messages in the same block, plus vanilla JS keplr

### PR DESCRIPTION
**Pull request by levackt**
There's been a discord discussion around whether this works, so this new example shows how to batch contract txs from the same account in the same block.
Renamed an example to match the other batch example, and cos it's not using multiExecute anymore

### CODE REVIEW

**Comment by assafmo** [comment]
I think it already works on the [update-secretjs](https://github.com/scrtlabs/SecretJS-Templates/tree/update-secretjs) branch. Can you take a look and maybe continue 5-8 there?

**Comment by levackt** [comment]
I actually branched off there, and 5-8 was already merged into that branch while you were on leave I think.

**Comment by levackt** [comment]
So this is just another variation, and the only example not working atm is the vanilla JS keplr

**Comment by assafmo** [comment]
Oh cool!!

**Comment by assafmo** [comment]
So if 5-8 are implemented 7 working let's merge into master

**Comment by assafmo** [comment]
Oh it's already there :sweat_smile:

**Comment by levackt** [comment]
Piggybacked the vanilla JS keplr, that should wrap it up for now.
If you're happy we can merge into your branch, and into master

**Comment by assafmo** [comment]
Thanks!

**Pull request merged**
