### PR TITLE
WIP: supernova-1

### PR DESCRIPTION
**Pull request by levackt**
Testing against supernova-1 locally, basic txs work but not all examples are working yet. Seems to relate to the signer.

Like contract upload, which fails as follows;

> Error: Error when posting tx 06BBA97C79C7F3AB481D205F333706127D8AB63EAAC5121DD4523271FC49731B. Code: 4; Raw log: signature verification failed; please verify account number (0), sequence (14) and chain-id (supernova-1): unauthorized
    at SigningCosmWasmClient.postTx (/Users/taariq/code/secret/SecretJS-Templates/node_modules/secretjs/build/cosmwasmclient.js:163:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async SigningCosmWasmClient.upload (/Users/taariq/code/secret/SecretJS-Templates/node_modules/secretjs/build/signingcosmwasmclient.js:142:24)
    at async main (/Users/taariq/code/secret/SecretJS-Templates/5_contracts/main.js:62:25) 
    
    
Still looking into this, but if you're reading this and want to reproduce it, or suggest a fix

1. run supernova-1 with docker
`docker run -it --rm \                                                                     ─╯
 -p 26657:26657 -p 26656:26656 -p 1337:1337 \
 -v $(pwd):/root/code \
 --name secretdev-supernova-1 enigmampc/secret-network-sw-dev:supernova-1`    
 
2. copy the mnemonic from one of the accounts logged above, or send some funds to a new account, and update your .env accordingly. Also set chain-id to supernova-1 

3. install the latest secretJS 
`npm i`

4. run the contracts example
`npm run 5`

### CODE REVIEW

**Comment by levackt** [comment]
Jumped the gun on this, will reopen later

**Comment by levackt** [comment]
@assafmo, maybe you spot something, I've just upgraded secretjs to "0.17.4-beta1" and tried to run all examples, failing on 5 and 7 so far.

Anyway, I've now moved on from the upload error mentioned in description, by passing in some codeMeta. So first, is it intentional for upload to fail with empty codeMeta now?

Next error is now on instantiate, same message as before, the error log wasn't decrypted.

**Comment by assafmo** [comment]
Weird, I'll take a look, thanks for reporting.

**Comment by levackt** [comment]
With the update to 0.17.3 from earlier, its mostly working again, just need to update keplr and then websocket examples. This version is already enough to update Figment so will do so shortly.

Also a headsup, I had to recover 2FA and in doing so I'm no longer a collaborator and cannot update this branch. Let me know if you can add me again, else I'll make a fork to submit the PR.

Thanks @assafmo

**Comment by levackt** [comment]
Superseded by #26

**Pull request closed without merging**
