### PR TITLE
Update secretjs, and increase gas

### PR DESCRIPTION
**Pull request by levackt**
Updated to latest in npm.
NB Example 7 still fails, besides increasing gas, fromUtf8 of the data for the create_viewing_key no longer works. 
Will check it out on the weekend, any hints appreciated :)

### CODE REVIEW

**Comment by assafmo** [comment]
After Shockwave Delta you now have to use `MsgExecuteContractResponse.decode()` to decode the output data.
Example: https://github.com/scrtlabs/secret.js/blob/9e0ad0b/test/test.ts#L261-L263

**Comment by levackt** [comment]
Should I be able to require it from secretjs?

Because if I use `const {MsgExecuteContractResponse} = require("secretjs/src/protobuf_stuff/secret/compute/v1beta1/msg");` then it fails with module not found

**Comment by assafmo** [comment]
That works:
```
import { MsgExecuteContractResponse } from "secretjs/dist/protobuf_stuff/secret/compute/v1beta1/msg";
```
However I'll export it from the main package.

**Comment by assafmo** [comment]
Should now be available from the top level of v1.4.5.

**Comment by levackt** [comment]
Fixed in new PR, thanks

**Pull request closed without merging**
