### PR TITLE
update secretjs package and secretdev docker image

### PR DESCRIPTION
**Pull request by levackt**
Draft while fromJSON still produces this error when you run `npm run 4` or `npm run 7`;

> /Users/taariq/code/secret/myfork/SecretJS-Templates/node_modules/secretjs/build/ProtoEncoding.js:22
    const root = minimal_1.default.Root.fromJSON(JSON.parse(descriptor));
                                        ^

> TypeError: Cannot read property 'fromJSON' of undefined
    at Object.decodeTxData (/Users/taariq/code/secret/myfork/SecretJS-Templates/node_modules/secretjs/build/ProtoEncoding.js:22:41)
    at SigningCosmWasmClient.execute (/Users/taariq/code/secret/myfork/SecretJS-Templates/node_modules/secretjs/build/signingcosmwasmclient.js:365:48)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async main (/Users/taariq/code/secret/myfork/SecretJS-Templates/7_snip20_token/main.js:89:16)

### CODE REVIEW

**Comment by levackt** [comment]
[also linked to this issue](https://github.com/scrtlabs/SecretNetwork/issues/856)

**Comment by assafmo** [comment]
https://github.com/scrtlabs/SecretNetwork/issues/856#issuecomment-981688052

**Comment by assafmo** [comment]
Please try `sercetjs@0.17.5`

**Comment by levackt** [comment]
At the moment only batch tx sending isn't working for me, and only for multiple txs for the same account isn't broadcast, whereas multiple messages in a single tx works.

`npm run 4:batch`

**Comment by levackt** [comment]
Removed the batch example using account sequence because it doesn't work since cosmos sdk v0.38, see [this thread for details](https://forum.cosmos.network/t/sending-txs-multiple-times-in-quick-succession-from-the-same-sender-account-fails/3363/3)

Also updated for pulsar-2 env

**Comment by agent-mili** [comment]
I support this PR, wanted to do pretty much same PR.

**Comment by levackt** [comment]
new PR in progress

**Pull request closed without merging**
